/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;



import controlador.ControladorSandwicheria;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import modelo.Pedido;
import modelo.Turno;
import static vista.VentanaComandas.jTComandas;
import static vista.VentanaComprobantes.jLNeto;
import static vista.VentanaComprobantes.jLNumFactura;
import static vista.VentanaComprobantes.jLTotalFac;
import static vista.VentanaPedido.MostrarBotonesBarraBaja;
import static vista.VentanaPedido.OcultarBotonesBarraBaja;
import static vista.VentanaTurnos.jLCantPedidos;
import static vista.VentanaTurnos.jLTotRecaudado;

/**
 *
 * @author conty
 */
public class VentanaPedidos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPedidos
     */
    public static Pedido pedido = null;
    
    public VentanaPedidos() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        VentanaPedido.PanelInfoNegocio();
        VentanaPedido.PanelCondTrib();
        VentanaPedido.IniciarPedido();
        VentanaPedido.FinTurno();
        
        DefaultTableModel datosInicio = (DefaultTableModel) jTable1.getModel();
        TableColumnModel columnModel = jTable1.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(20); 
        columnModel.getColumn(1).setPreferredWidth(100);
        columnModel.getColumn(2).setPreferredWidth(20);
        columnModel.getColumn(3).setPreferredWidth(50);
        ControladorSandwicheria.mostrarProductosDisponibles(datosInicio);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLNombreNegocio = new javax.swing.JLabel();
        jLDireccionNegocio = new javax.swing.JLabel();
        jLTelefonoNegocio = new javax.swing.JLabel();
        jLFechaNegocio = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLHoraNegocio = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLNombreCajero = new javax.swing.JLabel();
        jLLegajoCajero = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLTurnoCajero = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLTituloProductos = new javax.swing.JLabel();
        jBAgregados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLTituloCantidad = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        jLTituloAgregados = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAgregPorDefec = new javax.swing.JTable();
        jLTituloPorDefecto = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTAgregGene = new javax.swing.JTable();
        jLTituloGenerales = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTAgregEspe = new javax.swing.JTable();
        jLTituloSandwich = new javax.swing.JLabel();
        jBCancelar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTDetallePedido = new javax.swing.JTable();
        jLTituloTotal = new javax.swing.JLabel();
        jLTotal = new javax.swing.JLabel();
        jBEliminarConcepto = new javax.swing.JButton();
        jBCancelarPedido = new javax.swing.JButton();
        jBContinuarComa = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLCondTribuDueño = new javax.swing.JLabel();
        jLCondTribuCliente = new javax.swing.JLabel();
        jLConcepto = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jBCambiar = new javax.swing.JButton();
        jBFinalizarTurno = new javax.swing.JButton();
        jBAgregPed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Pedido");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLNombreNegocio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLNombreNegocio.setText("NOMBRE");

        jLDireccionNegocio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLDireccionNegocio.setText("DIRECCION");

        jLTelefonoNegocio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLTelefonoNegocio.setText("TELEFONO");

        jLFechaNegocio.setText("jLabel5");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("FECHA");

        jLHoraNegocio.setText("jLabel7");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("HORA");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("CAJERO:");

        jLNombreCajero.setText("NOMBRE CAJERO");

        jLLegajoCajero.setText("LEGAJO");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("TURNO:");

        jLTurnoCajero.setText("TURNO CAJERO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLTelefonoNegocio)
                        .addGap(315, 315, 315))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLDireccionNegocio)
                            .addComponent(jLNombreNegocio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLFechaNegocio)
                            .addComponent(jLHoraNegocio))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLTurnoCajero))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLNombreCajero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLLegajoCajero)))
                        .addContainerGap(15, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombreNegocio)
                    .addComponent(jLFechaNegocio)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLNombreCajero)
                    .addComponent(jLLegajoCajero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDireccionNegocio)
                    .addComponent(jLabel8)
                    .addComponent(jLHoraNegocio)
                    .addComponent(jLabel10)
                    .addComponent(jLTurnoCajero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLTelefonoNegocio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLTituloProductos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLTituloProductos.setText("PRODUCTOS");

        jBAgregados.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBAgregados.setText("AÑADIR AGREGADOS");
        jBAgregados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregadosActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CUP", "Nombre", " ", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLTituloCantidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLTituloCantidad.setText("CANTIDAD");

        jSpinner1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTituloProductos)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLTituloCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jBAgregados)
                        .addGap(112, 112, 112))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTituloProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAgregados)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTituloCantidad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLTituloAgregados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLTituloAgregados.setText("AGREGADOS");

        jTAgregPorDefec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", " "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTAgregPorDefec);

        jLTituloPorDefecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLTituloPorDefecto.setText("Por defecto");

        jTAgregGene.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", " "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTAgregGene);

        jLTituloGenerales.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLTituloGenerales.setText("Generales");

        jTAgregEspe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", " "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTAgregEspe);

        jLTituloSandwich.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jBCancelar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBCancelar.setText("CANCELAR");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTituloAgregados)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLTituloPorDefecto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLTituloGenerales))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLTituloSandwich, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jBCancelar))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTituloAgregados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLTituloGenerales)
                        .addComponent(jLTituloSandwich, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLTituloPorDefecto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Detalle del Pedido");

        jTDetallePedido.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTDetallePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CUP", "Cantidad", "Nombre Prod", "Precio Prod", "Agregados", "Precio Agreg", "Subtotal"
            }
        ));
        jScrollPane5.setViewportView(jTDetallePedido);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLTituloTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLTituloTotal.setText("TOTAL");

        jLTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBEliminarConcepto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBEliminarConcepto.setText("ELIMINAR CONCEPTO");
        jBEliminarConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarConceptoActionPerformed(evt);
            }
        });

        jBCancelarPedido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBCancelarPedido.setText("CANCELAR PEDIDO");
        jBCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarPedidoActionPerformed(evt);
            }
        });

        jBContinuarComa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBContinuarComa.setText("CONTINUAR");
        jBContinuarComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBContinuarComaActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLCondTribuDueño.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLCondTribuDueño.setText("COND. TRIB. DUEÑO");

        jLCondTribuCliente.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLCondTribuCliente.setText("COND. TRIB. CLIENTE");

        jLConcepto.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLConcepto.setText("CONCEPTO");

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CONSUMIDOR FINAL", "MONOTRIBUTISTA", "RESPONSABLE INSCRIPTO", "EXENTO", "NO RESPONSABLE" }));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MONOTRIBUTISTA", "RESPONSABLE INSCRIPTO", "EXENTO", "NO RESPONSABLE" }));

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRODUCTOS", "SERVICIOS", "PRODUCTOS Y SERVICIOS" }));

        jBCambiar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBCambiar.setText("CAMBIAR");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLCondTribuDueño)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLConcepto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBCambiar)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLCondTribuCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCondTribuDueño)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCondTribuCliente)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLConcepto)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCambiar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jBFinalizarTurno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBFinalizarTurno.setText("FINALIZAR TURNO");
        jBFinalizarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFinalizarTurnoActionPerformed(evt);
            }
        });

        jBAgregPed.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBAgregPed.setText("AGREGAR AL PEDIDO");
        jBAgregPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregPedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(208, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBAgregPed)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLTituloTotal)
                                .addGap(18, 18, 18)
                                .addComponent(jLTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126)
                                .addComponent(jBEliminarConcepto)
                                .addGap(153, 153, 153)
                                .addComponent(jBCancelarPedido)
                                .addGap(150, 150, 150)
                                .addComponent(jBFinalizarTurno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBContinuarComa))
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jBAgregPed)
                .addGap(11, 11, 11)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBFinalizarTurno)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBContinuarComa)
                        .addComponent(jBEliminarConcepto)
                        .addComponent(jLTituloTotal)
                        .addComponent(jBCancelarPedido))
                    .addComponent(jLTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAgregadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregadosActionPerformed
        // TODO add your handling code here:
        DefaultTableModel datos1 = (DefaultTableModel) jTAgregPorDefec.getModel();
        DefaultTableModel datos2 = (DefaultTableModel) jTAgregGene.getModel();
        DefaultTableModel datos3 = (DefaultTableModel) jTAgregEspe.getModel();
        int cont = 0;
        String CUPProducto = null;
        Boolean checked = false;
        for(int i = 0; i < jTable1.getRowCount(); i++){
            checked = Boolean.valueOf(jTable1.getValueAt(i,2).toString());
            if(checked){
                cont = cont + 1;
                CUPProducto = String.valueOf(jTable1.getValueAt(i,0));
            }
        }
        String nombreTabla = ControladorSandwicheria.AñadirAgregados(cont, CUPProducto, datos1, datos2, datos3);
        jLTituloSandwich.setText(nombreTabla);
    }//GEN-LAST:event_jBAgregadosActionPerformed

    private void jBEliminarConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarConceptoActionPerformed
        // TODO add your handling code here:
        DefaultTableModel datos = (DefaultTableModel) jTDetallePedido.getModel();
        int filaSeleccionada = jTDetallePedido.getSelectedRow();
        double total = ControladorSandwicheria.EliminarConcepto(datos,filaSeleccionada,pedido);
        jLTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_jBEliminarConceptoActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        int contador = 0;
        DefaultTableModel datosInicio = (DefaultTableModel) jTable1.getModel();
        DefaultTableModel datos1 = (DefaultTableModel) jTAgregPorDefec.getModel();
        DefaultTableModel datos2 = (DefaultTableModel) jTAgregGene.getModel();
        DefaultTableModel datos3 = (DefaultTableModel) jTAgregEspe.getModel();
        DefaultTableModel datos4 = (DefaultTableModel) jTDetallePedido.getModel();
        ControladorSandwicheria.LimpiarTablas(datosInicio, datos1, datos2, datos3);
        for (int i = 0; i < datos4.getRowCount(); i++) {
            contador = contador + 1;
        }
        if (contador > 0){
            MostrarBotonesBarraBaja();
        }
        else{
            OcultarBotonesBarraBaja();
        }
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarPedidoActionPerformed
        // TODO add your handling code here:
        DefaultTableModel datosInicio = (DefaultTableModel) jTable1.getModel();
        DefaultTableModel datos1 = (DefaultTableModel) jTAgregPorDefec.getModel();
        DefaultTableModel datos2 = (DefaultTableModel) jTAgregGene.getModel();
        DefaultTableModel datos3 = (DefaultTableModel) jTAgregEspe.getModel();
        DefaultTableModel datos4 = (DefaultTableModel) jTDetallePedido.getModel();
        ControladorSandwicheria.CancelarPedido(pedido, datosInicio, datos1, datos2, datos3, datos4);
        jLTotal.setText("");
    }//GEN-LAST:event_jBCancelarPedidoActionPerformed

    private void jBContinuarComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBContinuarComaActionPerformed
        // TODO add your handling code here:
        Pedido.agregarPedidoANeg(pedido);
        int numComprobante = ControladorSandwicheria.NuevoComprobante(pedido.getMontototalpedido());
        DefaultTableModel datos = (DefaultTableModel) jTDetallePedido.getModel();
        DefaultTableModel datosComanda = (DefaultTableModel) jTComandas.getModel();
        ControladorSandwicheria.PasarDatosaDetalleComanda(datos, datosComanda);
        ControladorSandwicheria.VentanaComanda();
        jLNeto.setText(String.valueOf(pedido.getMontonetopedido()));
        jLTotalFac.setText(String.valueOf(pedido.getMontototalpedido()));
        jLNumFactura.setText("0000000" + Integer.toString(numComprobante));
    }//GEN-LAST:event_jBContinuarComaActionPerformed

    private void jBAgregPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregPedActionPerformed
        // TODO add your handling code here:
        DefaultTableModel datosInicio = (DefaultTableModel) jTable1.getModel();
        DefaultTableModel datos1 = (DefaultTableModel) jTAgregPorDefec.getModel();
        DefaultTableModel datos2 = (DefaultTableModel) jTAgregGene.getModel();
        DefaultTableModel datos3 = (DefaultTableModel) jTAgregEspe.getModel();
        DefaultTableModel datos4 = (DefaultTableModel) jTDetallePedido.getModel();
        int cont = 0;
        int seleccionado = 0;
        String CUPProducto = null;
        Boolean checked = false;
        for(int i = 0; i < jTable1.getRowCount(); i++){
            checked = Boolean.valueOf(jTable1.getValueAt(i,2).toString());
            if(checked){
                cont = cont + 1;
                seleccionado = i;
                CUPProducto = String.valueOf(jTable1.getValueAt(i,0));
            }
        }
        int cantidad = (int) jSpinner1.getValue();
        ControladorSandwicheria.addProductoADetalledePedido(cont, seleccionado, CUPProducto, cantidad, datosInicio, datos1, datos2, datos3, datos4, pedido);
        jLTotal.setText(String.valueOf(ControladorSandwicheria.getTotal()));
    }//GEN-LAST:event_jBAgregPedActionPerformed

    private void jBFinalizarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFinalizarTurnoActionPerformed
        // TODO add your handling code here:
        jLCantPedidos.setText(Integer.toString(Turno.controlAcu));
        jLTotRecaudado.setText(Double.toString(Turno.totalPed));
        ControladorSandwicheria.VentanaTurno();
    }//GEN-LAST:event_jBFinalizarTurnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jBAgregPed;
    public static javax.swing.JButton jBAgregados;
    public static javax.swing.JButton jBCambiar;
    public static javax.swing.JButton jBCancelar;
    public static javax.swing.JButton jBCancelarPedido;
    public static javax.swing.JButton jBContinuarComa;
    public static javax.swing.JButton jBEliminarConcepto;
    public static javax.swing.JButton jBFinalizarTurno;
    public static javax.swing.JComboBox<String> jComboBox1;
    public static javax.swing.JComboBox<String> jComboBox2;
    public static javax.swing.JComboBox<String> jComboBox3;
    public static javax.swing.JLabel jLConcepto;
    public static javax.swing.JLabel jLCondTribuCliente;
    public static javax.swing.JLabel jLCondTribuDueño;
    public static javax.swing.JLabel jLDireccionNegocio;
    public static javax.swing.JLabel jLFechaNegocio;
    public static javax.swing.JLabel jLHoraNegocio;
    public static javax.swing.JLabel jLLegajoCajero;
    public static javax.swing.JLabel jLNombreCajero;
    public static javax.swing.JLabel jLNombreNegocio;
    public static javax.swing.JLabel jLTelefonoNegocio;
    public static javax.swing.JLabel jLTituloAgregados;
    public static javax.swing.JLabel jLTituloCantidad;
    public static javax.swing.JLabel jLTituloGenerales;
    public static javax.swing.JLabel jLTituloPorDefecto;
    public static javax.swing.JLabel jLTituloProductos;
    public static javax.swing.JLabel jLTituloSandwich;
    public static javax.swing.JLabel jLTituloTotal;
    public static javax.swing.JLabel jLTotal;
    public static javax.swing.JLabel jLTurnoCajero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel4;
    public static javax.swing.JPanel jPanel5;
    public static javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public static javax.swing.JSpinner jSpinner1;
    public static javax.swing.JTable jTAgregEspe;
    public static javax.swing.JTable jTAgregGene;
    public static javax.swing.JTable jTAgregPorDefec;
    public static javax.swing.JTable jTDetallePedido;
    public static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
